package Dao;
// Generated 27/03/2016 09:07:55 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String nombre;
     private String contraseña;

    public Usuario() {
    }

	
    public Usuario(String nombre) {
        this.nombre = nombre;
    }
    public Usuario(String nombre, String contraseña) {
       this.nombre = nombre;
       this.contraseña = contraseña;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContraseña() {
        return this.contraseña;
    }
    
    public void setContraseña(String contraseña) {
        this.contraseña = contraseña;
    }




}


